### ISSUE TITLE
[ERROR] Could not find tool when uploading

### ISSUE THREAD

**Issue by novvere** [Wiz-IO/framework-sam-lora#1]
Hi Georgi,
I'm testing RAK4260 board to make it work with LoRaWAN and TTN using Arduino framework. 
I have been to install the new  platformio  framework, compiled bootloader and install it in the board using j-flash lite.
But when I try to upload your Hello world example from your repository I always get the following message:

>Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
>DATA:    [          ]   4.3% (used 1704 bytes from 40000 bytes)
>PROGRAM: [==        ]  17.8% (used 45596 bytes from 256000 bytes)
>Configuring upload protocol...
>
>
>ERASING
>[ERROR] Could not find tool.
>
>*** [upload] Explicit exit, status 1
>

I tried uploading the example with the usb interface and by SWD header through j-link with the same result.

Which is the correct way to upload the program? usb? SWD? am I missing something?

Thanks
Miguel

**Comment by Wiz-IO** [comment]
Hi
I not support RAK4260
Microchip XPRO have on-board swd **edbg**  ...
Platform generate bin and hex files - upload with any stand alone tool

**Comment by novvere** [comment]
Thanks, it worked fine using an external tool.

**Comment by Wiz-IO** [comment]
:+1: 
I not have RAK4260 and can not do tests

**Comment by novvere** [comment]
Tell me if you need me to test anything, here in The Things Network Madrid we are interested in using this chip with Arduino framework (not all the people is able to write navite  c++ with Atmel Studio).
We would like to test LoRaWAN and some sensors (accelerometer, gps, temp and humidity, etc)

**Comment by Wiz-IO** [comment]
Тhe project is very much the beginning
not everything works... I think gpio, serial,i2c and spi work - you can test sensors
RF use spi, but is not ready... 
for LoRaWAN need library

**Comment by novvere** [comment]
ok, I will spend some time in your code to find things I can help you on, the easiest will be to check and make some samples on gpio and i2c.
LoRaWAN library have to be written from scratch? is just a wrapper around an existing one?

**Comment by Wiz-IO** [comment]
Arduino libraries must work... 
for LoraWAN have libraries, the chip inside is "normal" sx1276

**Comment by Wiz-IO** [comment]
you can test RF
https://github.com/Wiz-IO/framework-sam-lora/tree/master/examples/arduino_simple_lora

**Comment by Wiz-IO** [comment]
and LoRaWAN
https://github.com/Wiz-IO/framework-sam-lora/tree/master/examples/arduino_beelan_lorawan

I not have LoRaWAN cell

**Comment by novvere** [comment]
The node resets on every loop, always initialising and trying to send counter 0 and no message is shown in gateway console.
I will try to debug and will open another separate issue.

**Comment by Wiz-IO** [comment]
look this
https://github.com/Wiz-IO/framework-sam-lora/blob/master/arduino/libraries/Beelan-LoRaWAN/src/arduino-rfm/Config.h#L9
