### ISSUE TITLE
Copile  error when setting EU868

### ISSUE THREAD

**Issue by novvere** [Wiz-IO/framework-sam-lora#2]
There is an error in the name of an attribute when defining EU868 band in config file.
\.platformio\packages\framework-sam-lora\arduino\libraries\Beelan-LoRaWAN\src\arduino-rfm\Config.h

**Comment by novvere** [comment]
In .platformio\packages\framework-sam-lora\arduino\libraries\Beelan-LoRaWAN\src\arduino-rfm\lorawan-arduino-rfm.cpp line 287 the attribute name must be changed by:
LoRa_Settings.Datarate_Tx = drate_common;

**Comment by Wiz-IO** [comment]
will update lib soon
