### ISSUE TITLE
Board reset when transmitting LoRa Message

### ISSUE THREAD

**Issue by novvere** [Wiz-IO/framework-sam-lora#3]
Changes band to EU868.
Compiled and uploaded firmware to board.
The board always reboot when trying to send a LoRa message, just after writing 0x83 value in 0x01 radio module register.
This is the bug information generated:

RF Write ADDR: 1 DATA: 83       RXSINGLE
SAMR34 Arduino 2019 Georgi Angelov               Reset!!!

**Comment by Wiz-IO** [comment]
The Reset are a consequence of the watchdog ( enable by default )
Some "bug" make "loop forever"...

**Comment by Wiz-IO** [comment]
![appdata](https://user-images.githubusercontent.com/14574834/69616404-3831e700-103f-11ea-81fc-b8ba6bf4db63.png)

**Comment by novvere** [comment]
I see it resets always after waiting for TxDone.
```
//Wait for TxDone
  while(digitalRead(RFM_pins.DIO0) == LOW);
```
But no message arrives to any of the gateways.
Any way to disable watchdog to test?

**Comment by Wiz-IO** [comment]
comment
https://github.com/Wiz-IO/framework-sam-lora/blob/master/arduino/variants/samr34xpro/system.c#L34

**Comment by novvere** [comment]
It always hangs when waiting RFM_pins.DIO0 to be HIGH.
But at least you are been able to send a message. I don't.

**Comment by Wiz-IO** [comment]
yep :)
your **TCXO_PWR_PIN is_PORTB 3** and RF oscilator cannot start ... 
Microchip XPRO board use PORTA  9
https://github.com/Wiz-IO/framework-sam-lora/blob/master/arduino/variants/samr34xpro/variant.cpp#L111

**Comment by novvere** [comment]
That's what I was trying to find out, at the beginning I suppose all SAMR34 use the same pinout to communicate MCU with radio module.
Now it works, no hangs and I see messages in ttn console, I will try now OTAA and multi channel.
Thanks!!!!
