### ISSUE TITLE
Only US_915 data rate values are defined.

### ISSUE THREAD

**Issue by novvere** [Wiz-IO/framework-sam-lora#4]
The data rate definition for EU8688 is missing in struct.h. The US_915 is always used so using SF7BW125 is really using SF9W125.

I solved te problems defining the structure like:
```
typedef enum {
#ifdef US_915
    SF10BW125   = 0x00,
    SF9BW125    = 0x01,
    SF8BW125    = 0x02,
    SF7BW125    = 0x03,
    SF8BW500    = 0x04,
    SF12BW500   = 0x08,
    SF11BW500   = 0x09,
    SF10BW500   = 0x0A,
    SF9BW500    = 0x0B,
    SF7BW500    = 0x0D
#elif defined(EU_868)
    SF12BW125   = 0x00,
    SF11BW125   = 0x01,
    SF10BW125   = 0x02,
    SF9BW125    = 0x03,
    SF8BW125    = 0x04,
    SF7BW125    = 0x05
#endif
} dataRates_t;
```

**Comment by Wiz-IO** [comment]
what source

**Comment by Wiz-IO** [comment]
???
https://github.com/Wiz-IO/framework-sam-lora/blob/master/arduino/libraries/Beelan-LoRaWAN/src/arduino-rfm/Struct.h#L110

**Comment by novvere** [comment]
Sorry, the pah is:

.platformio\packages\framework-sam-lora\arduino\libraries\Beelan-LoRaWAN\src\arduino-rfm\Struct.h

**Comment by Wiz-IO** [comment]
done
